apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.express.name }}
spec:
  replicas: {{ .Values.express.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.express.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.express.app }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Values.express.serviceAccount }}
      initContainers:
        - name: copy-vault-secrets
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              cp /mnt/vault/* /mnt/runtime/
          volumeMounts:
            - name: vault-secrets
              mountPath: /mnt/vault
              readOnly: true
            - name: runtime-secrets
              mountPath: /mnt/runtime
      containers:
        - name: {{ .Values.express.name }}
          image: {{ .Values.express.image }}:{{ .Values.express.version }}
          imagePullPolicy: {{ .Values.express.pullPolicy }}
          ports:
            - containerPort: {{ .Values.express.targetPort }}
          env:
            {{- range $key, $value := .Values.express.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: APP_DB_HOST
              value: {{ .Values.appDb.app }}
            - name: APP_DB_PORT
              value: "{{ .Values.appDb.port }}"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: runtime-secrets
              mountPath: /mnt/runtime-secrets
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "express-secrets"
        - name: runtime-secrets
          emptyDir: {}