apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.express.name }}
spec:
  selector:
    app: {{ .Values.express.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.express.port }}
      targetPort: {{ .Values.express.targetPort }}
