apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.keycloak.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.keycloak.app }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: keycloak-sa
      containers:
        - name: {{ .Values.keycloak.name }}
          image: {{ .Values.keycloak.image }}:{{ .Values.keycloak.version }}
          imagePullPolicy: {{ .Values.keycloak.pullPolicy }}
          ports:
            - containerPort: {{ .Values.keycloak.port }}
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: {{ .Values.keycloakDb.app }}
            - name: KC_DB_URL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: keycloak-k8s-secret
                  key: KC_DB_URL_DATABASE
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-k8s-secret
                  key: KC_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-k8s-secret
                  key: KC_DB_PASSWORD
            #- name: KC_BOOTSTRAP_ADMIN_USERNAME
            #  value: {{ .Values.keycloak.adminUser }}
            #- name: KC_BOOTSTRAP_ADMIN_PASSWORD
            #  value: {{ .Values.keycloak.adminPassword }}
            - name: EXTERNAL_DB_HOST
              value: {{ .Values.appDb.app }}
            - name: EXTERNAL_DB_PORT
              value: "{{ .Values.appDb.port }}"
            - name: EXTERNAL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-k8s-secret
                  key: APP_DB_NAME
            - name: EXTERNAL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-k8s-secret
                  key: APP_DB_USER
            - name: EXTERNAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-k8s-secret
                  key: APP_DB_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
              value: "false"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: vault-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: keycloak-tmp
              mountPath: /opt/keycloak/data/tmp
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keycloak-secrets"
        - name: tmp
          emptyDir: {}
        - name: keycloak-tmp
          emptyDir: {}
