apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
  namespace: app
spec:
  selector:
    app: {{ .Values.keycloak.app }}
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}
      protocol: TCP