apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appDb.pv.name }}
  labels:
    app: {{ .Values.appDb.app }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appDb.pvc.name }}
  labels:
    app: {{ .Values.appDb.app }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
