apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appDb.name }}
spec:
  selector:
    app: {{ .Values.appDb.app }}
  ports:
    - port: {{ .Values.appDb.port }}
      targetPort: {{ .Values.appDb.targetPort }}