apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.express.serviceAccount }}
  namespace: app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.keycloak.serviceAccount }}
  namespace: app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.keycloakDb.serviceAccount }}
  namespace: app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appDb.serviceAccount }}
  namespace: app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-sa
  namespace: cert-manager
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
automountServiceAccountToken: false