tetragon:
  enabled: true
  enableK8sAPIAccess: true
  export:
    # Abilita esportazione in Loki
    json: true
    logLevel: info
    logToStdout: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
  enableProcessCred: true
