---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: express-secrets
  namespace: app
spec:
  provider: vault
  parameters:
    roleName: "express-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "MAILGUN_DOMAIN"
        secretPath: "secret/data/express"
        secretKey: "MAILGUN_DOMAIN"
      - objectName: "EMAIL_RESET_SECRET"
        secretPath: "secret/data/express"
        secretKey: "EMAIL_RESET_SECRET"
      - objectName: "EMAIL_VERIFY_SECRET"
        secretPath: "secret/data/express"
        secretKey: "EMAIL_VERIFY_SECRET"
      - objectName: "MAILGUN_API_KEY"
        secretPath: "secret/data/express"
        secretKey: "MAILGUN_API_KEY"
      - objectName: "GOOGLE_CLIENT_ID"
        secretPath: "secret/data/express"
        secretKey: "GOOGLE_CLIENT_ID"
      - objectName: "GOOGLE_CLIENT_SECRET"
        secretPath: "secret/data/express"
        secretKey: "GOOGLE_CLIENT_SECRET"
      - objectName: "PASSWORD_SECRET"
        secretPath: "secret/data/express"
        secretKey: "PASSWORD_SECRET"
      - objectName: "KC_CLIENT_ID"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_CLIENT_ID"
      - objectName: "KC_CLIENT_SECRET"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_CLIENT_SECRET"
      - objectName: "KC_CLIENT_ID_WAN"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_CLIENT_ID_WAN"
      - objectName: "KC_CLIENT_SECRET_WAN"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_CLIENT_SECRET_WAN"
      - objectName: "KC_CLIENT_ID_FED"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_CLIENT_ID_FED"
      - objectName: "KC_CLIENT_SECRET_FED"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_CLIENT_SECRET_FED"
      - objectName: "KC_HOSTNAME"
        secretPath: "secret/data/keycloak"
        secretKey: "KC_HOSTNAME"
      - objectName: "APP_DB_NAME"
        secretPath: "secret/data/app-db"
        secretKey: "name"
      - objectName: "APP_DB_USER"
        secretPath: "secret/data/app-db"
        secretKey: "user"
      - objectName: "APP_DB_PASSWORD"
        secretPath: "secret/data/app-db"
        secretKey: "password"
