---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whitelist-updater
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: whitelist-updater-role
  namespace: monitoring
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whitelist-updater-binding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: whitelist-updater
    namespace: monitoring
roleRef:
  kind: Role
  name: whitelist-updater-role
  apiGroup: rbac.authorization.k8s.io
---
# Permessi su app
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: whitelist-updater-role
  namespace: app
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whitelist-updater-binding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: whitelist-updater
    namespace: monitoring
roleRef:
  kind: Role
  name: whitelist-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: whitelist-updater-role
  namespace: vault
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whitelist-updater-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: whitelist-updater
    namespace: monitoring
roleRef:
  kind: Role
  name: whitelist-updater-role
  apiGroup: rbac.authorization.k8s.io